[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "terrorblade"
version = "0.1.0"
description = "A Python-based Telegram message parser and analyzer"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
authors = [
    { name = "Vsevolod Prudius", email = "sevapru@gmail.com" }
]
dependencies = [
    "polars",
    "pandas",
    "telethon",
    "duckdb",
    "vllm",
    "python-dotenv",
    "beautifulsoup4",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "mypy",
]

[tool.hatch.build.targets.wheel]
packages = ["terrorblade"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true