[project]
name = "terrorblade"
version = "0.2.0"
description = "A Python-based Telegram message parser and analyzer"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
authors = [
    { name = "Vsevolod Prudius", email = "sevapru@gmail.com" }
]
dependencies = [
    "polars",
    "telethon",
    "duckdb",
    "vllm",
    "python-dotenv",
    "beautifulsoup4",
    "numpy",
    "sentence-transformers",
    "pyarrow",
    "seaborn",
]

[project.optional-dependencies]
dev = [
    "tomli",
    "packaging",
    "pytest",
    "black",
    "isort",
    "mypy",
]

cuda = [
    "cupy-cuda12x",
    "cudf-cu12==24.10.*",
    "dask-cudf-cu12==24.10.*",
    "cuml-cu12==24.10.*",
    "cugraph-cu12==24.10.*",
    "nx-cugraph-cu12==24.10.*",
    "cuspatial-cu12==24.10.*",
    "cuproj-cu12==24.10.*",
    "cuxfilter-cu12==24.10.*",
    "cucim-cu12==24.10.*",
    "pylibraft-cu12==24.10.*",
    "raft-dask-cu12==24.10.*",
    "cuvs-cu12==24.10.*",
]

[project.scripts]
terrorblade = "terrorblade.main:main"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.setuptools]
packages = ["terrorblade"]